# Generated by Django 5.0.2 on 2024-02-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/covers')),
            ],
        ),
    ]
