# Generated by Django 5.0.2 on 2024-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0004_dish_vegan'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_dish_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField()),
                ('dish_name', models.TextField()),
                ('price', models.IntegerField()),
                ('vegan', models.BooleanField()),
            ],
            options={
                'db_table': 'shop_dishes_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='shop',
            name='canteen_num',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='floor',
        ),
    ]
