# Generated by Django 5.0.2 on 2024-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0006_alter_shop_isselling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='isselling',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
