# Generated by Django 5.0.2 on 2024-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0007_alter_shop_isselling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='isselling',
            field=models.BooleanField(),
        ),
    ]
