# Generated by Django 5.0.2 on 2024-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0008_alter_shop_isselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='YUMMY!'),
            preserve_default=False,
        ),
    ]
