# Generated by Django 5.0.2 on 2024-02-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0009_dish_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
