# Generated by Django 5.0.2 on 2024-02-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0011_remove_stu_dorm_index_remove_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stu_num',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(default='ioidsaujhfuoash123flkjsdef'),
        ),
    ]
