# Generated by Django 5.0.2 on 2024-02-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0012_remove_user_admin_num_remove_user_emp_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='note',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbill',
            name='table',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='finished',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='host',
            field=models.OneToOneField(blank=True, db_column='ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iorder.user'),
        ),
    ]
