# Generated by Django 5.0.2 on 2024-02-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iorder', '0013_orderbill_note_orderbill_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbill',
            name='finished',
            field=models.TextField(),
        ),
    ]
